# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/
# https://github.com/poole/poole/issues/99 suggests to disable the following:
#relative_permalinks: true

# Setup
title: 'Reproducible Geosciences Discussion Forum @ AGILE 2017'
tagline: 'Reproducible Geosciences Discussion Forum'
description: 'Workshop at the <a href="https://agile-online.org/index.php/home-2017" title="conference website">20th AGILE International Conference on Geographic Information Science</a><br />Wageningen, May 9 2017'
url: http://o2r.info/agile-2017/
baseurl: /agile-2017/

keywords:
  - open access
  - open data
  - open source
  - reproducibility
  - reproducible research
  - giscience
  - gis
  - executable research
  - executable papers
  - one-click reproduce

author:
  name: 'workshop organization committee'
  url: http://o2r.info/agile-2017/

exclude: [README.md]

github:
  repo: https://github.com/o2r-project/agile-2017

# ribbon itself by https://github.com/simonwhitaker/github-fork-ribbon-css
ribbon:
  show: true
  text: 'Submit abstract'
  url: 'https://github.com/o2r-project/agile-2017#fork-destination-box'

#gems:
