# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/
# https://github.com/poole/poole/issues/99 suggests to disable the following:
#relative_permalinks: true

# Setup
title: 'Reproducible Research Workshops at AGILE'
tagline: 'Reproducible Research @ AGILE'
description: 'Workshop series at the <a href="https://agile-online.org/index.php/conference/" title="conference websites">AGILE International Conference on Geographic Information Science</a>'
url: https://o2r.info/reproducible-agile
baseurl: /reproducible-agile/

keywords:
  - open access
  - open data
  - open source
  - reproducibility
  - reproducible research
  - giscience
  - gis
  - executable research
  - executable papers
  - one-click reproduce

author:
  name: 'workshop organization committee'
  url: https://o2r.info/reproducible-agile/

exclude: [README.md, Gemfile, Gemfile.lock, Makefile]

github:
  repo: https://github.com/o2r-project/reproducible-agile/

# ribbon itself by https://github.com/simonwhitaker/github-fork-ribbon-css
ribbon:
  show: true
  text: 'RR Workshop 2019'
  url: 'https://o2r.info/reproducible-agile/2019/#registration'

gems:
  - jekyll-sitemap
